### PR TITLE
Add request plugin

### PR DESCRIPTION
**Pull request by yarkovaleksei**
@dotronglong Hello )) Added a new plugin for working with request elements. I described something similar here: https://github.com/dotronglong/faker/issues/38

### CODE REVIEW

**Comment by yarkovaleksei** [comment]
I didn’t increase the version, because I don’t know what you decide to do: 2.1.10 or 2.2.0

**Comment by dotronglong** [comment]
@yarkovaleksei I am so sorry for not respond promptly, I can see you make many changes in this PR, is that possible to explain me in details what you are going to release in this version? I understand that you referred to an issue in the past, is it applicable to give explanation and examples for what you are trying to make changes here. Once again, I would like to thank you for your contribution, and have a nice week ahead.

**Comment by yarkovaleksei** [comment]
@dotronglong These changes allow you to use some parts of the request object in the response. For example, a query parameter, title or url.
image

**Comment by yarkovaleksei** [comment]
@dotronglong I update version to 2.1.11

**Comment by dotronglong** [comment]
In case of missing data what will be returned? For example, `#request:query:not-found#` does not exist. @yarkovaleksei

**Comment by yarkovaleksei** [comment]
@dotronglong The string that could not be found will be returned. For example, the expression `#request:query:param2#` and links `/path?param=value` will be replaced with `param2`, because there is no parameter named `param2`.

**Comment by dotronglong** [comment]
@yarkovaleksei I appreciate the answer, but it doesn't sound good in my opinion, it might cause confusions when returning `param2` if `param2` does not exist. For example, how do we know if `param2` does not exist or it is actual value of existing `param2`? Do you have alternative solution for that?

**Comment by yarkovaleksei** [comment]
@dotronglong Then I would suggest leaving the expression in its entirety, not replacing it at all. So the user will clearly see that something is wrong. You can also display a message in the log, but few people read the logs.

**Comment by dotronglong** [comment]
@yarkovaleksei I agree that we should leave the expression if we don't have better solution for now in order to prevent confusions. Please let me know if you would do that. Thank you.

**Comment by yarkovaleksei** [comment]
@dotronglong I fix it ))

**Comment by dotronglong** [comment]
Thank you @yarkovaleksei , I would love if you can use version 2.2.0 since you introduced lots of changes here in files. In addition, do you see that you add enough tests which will help to cover all of possible scenarios and not breaking current code?

**Comment by yarkovaleksei** [comment]
@dotronglong Updated the version to 2.2.0. The old functionality is not affected, nothing is broken. The tests cover enough situations that may arise.

**Comment by yarkovaleksei** [comment]
I just need to add information to the Wiki, but I don't have edit access. Will you add a plugin description?

**Comment by yarkovaleksei** [comment]
@dotronglong Hello)) I just decided to remind myself. The proposed changes are tested, tests are written and cover all possible situations.

**Comment by dotronglong** [comment]
Thank you, I have just invited you as a collaborator, would you mind to check if it will allow you to edit wiki page? @yarkovaleksei

**Comment by yarkovaleksei** [comment]
Thank you for your confidence.  I will gladly help.

**Comment by yarkovaleksei** [comment]
@dotronglong Hello )) I've added a plugin description and usage examples to the Wiki page. Please take a look, and if everything is OK, then maybe you can accept my pull request?

https://github.com/dotronglong/faker/wiki/Plugins#request

**Comment by dotronglong** [comment]
That's great @yarkovaleksei , just one small note, it seems to have some syntax problems there, would you mind to check again?

**Comment by yarkovaleksei** [comment]
@dotronglong Are you talking about red text in json?  This is because regular json does not support comments.  I changed the language to json5 and everything is displayed correctly.

**Comment by dotronglong** [comment]
@yarkovaleksei I meant this
Screen Shot 2023-02-11 at 19 04 49

**Comment by yarkovaleksei** [comment]
@dotronglong I understand what you mean. Please look again at the page. I have changed the description and usage example.

**Pull request merged**
