### PR TITLE
Fix deep watching

### PR DESCRIPTION
**Pull request by yarkovaleksei**
@dotronglong Hello ))
I forgot in the [last pull request](https://github.com/dotronglong/faker/pull/41) to watch changes in nested directories. Now corrected.

### CODE REVIEW

**Comment by dotronglong** [comment]
Did you mean that watch feature will not support in the previous release? In that case, perhaps we should use version 2.1.10. Is that possible to attach your screenshot for which you tested on this feature on your local? Thank you.

**Comment by yarkovaleksei** [comment]
image

@dotronglong Hi )) This screenshot shows that when changing files that are deeper than the first level, the function is triggered.

**Comment by yarkovaleksei** [comment]
> Did you mean that watch feature will not support in the previous release?

No. Watching works, but only for first level files. My changes allow you to watch files at any level.

**Comment by dotronglong** [comment]
Thank you @yarkovaleksei , would you mind to set it to version 2.1.10?

**Comment by yarkovaleksei** [comment]
OK

**Comment by yarkovaleksei** [comment]
@dotronglong Version updated

**Pull request merged**
